/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --env-interface=GeneratedPartyEnv worker/env.d.ts` (hash: a08ed53a8e5b255a10a1f29674084f1a)
interface __BaseEnv_GeneratedPartyEnv {
	PARTY_HANDSHAKE_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "https://www.mistakes.party" | "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3100,http://127.0.0.1:3100";
	PARTY_MODE: "live";
	PARTY_GENERATION: "v1";
	PARTY_ROUTES: DurableObjectNamespace<import("./src/index").PartyRoute>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PartyRoute";
	}
	interface ProductionEnv {
		PARTY_HANDSHAKE_RATE_LIMITER: RateLimit;
		ALLOWED_ORIGINS: "https://www.mistakes.party";
		PARTY_MODE: "live";
		PARTY_GENERATION: "v1";
		PARTY_ROUTES: DurableObjectNamespace<import("./src/index").PartyRoute>;
	}
	interface Env extends __BaseEnv_GeneratedPartyEnv {}
}
interface GeneratedPartyEnv extends __BaseEnv_GeneratedPartyEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "PARTY_MODE" | "PARTY_GENERATION">> {}
}
